/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru') | ('en' | 'ru')[];
  globals: {
    'site-settings': SiteSetting;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: 'en' | 'ru';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'developer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?: {
    relationTo: 'users';
    value: number | User;
  } | null;
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Shown in the footer, on /contact, in the enquiry form, the Home FAQ card and the mobile contact bar.
   */
  contact: {
    /**
     * Exactly as visitors should read it, e.g. +971 58 809 9223.
     */
    phoneDisplay: string;
    /**
     * Same number in international format without spaces, e.g. +971588099223. Used for tap-to-call.
     */
    phoneE164: string;
    /**
     * Digits only with country code, e.g. 971588099223.
     */
    whatsappNumber: string;
    email: string;
    workingHours: string;
    /**
     * Where meetings take place. The site has no public office address.
     */
    visitsLine: string;
  };
  /**
   * The company line (footer, /contact) and the 'Who you are contracting with' block (/about) appear only when name, licence number and issuing authority are all filled in.
   */
  legal?: {
    entityName?: string | null;
    licenceNumber?: string | null;
    issuingAuthority?: string | null;
    activities?: string | null;
    registeredAddress?: string | null;
  };
  /**
   * Filled into the privacy notice (/privacy). A sentence that needs an empty value is left out.
   */
  privacy?: {
    contactEmail?: string | null;
    providers?: string | null;
    retention?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  header: {
    /**
     * The first menu item; it links to /services and opens the services panel.
     */
    servicesLabel: string;
    /**
     * Up to four columns, each with a heading and its services.
     */
    serviceGroups?:
      | {
          label: string;
          services: (
            | 'interior-design'
            | 'landscape-design'
            | 'villa-renovation'
            | 'apartment-renovation'
            | 'commercial-fit-out'
            | 'bespoke-joinery'
            | 'custom-kitchens'
            | 'wardrobes'
            | 'approvals'
            | 'mep-hvac'
            | 'materials-procurement'
          )[];
          id?: string | null;
        }[]
      | null;
    specialistLabel: string;
    specialistServices: (
      | 'interior-design'
      | 'landscape-design'
      | 'villa-renovation'
      | 'apartment-renovation'
      | 'commercial-fit-out'
      | 'bespoke-joinery'
      | 'custom-kitchens'
      | 'wardrobes'
      | 'approvals'
      | 'mep-hvac'
      | 'materials-procurement'
    )[];
    allServicesLabel: string;
    links?:
      | {
          label: string;
          route:
            | '/'
            | '/services'
            | '/projects'
            | '/process'
            | '/about'
            | '/insights'
            | '/contact'
            | '/warranty'
            | '/privacy'
            | '/cookies'
            | '/services/interior-design'
            | '/services/landscape-design'
            | '/services/villa-renovation'
            | '/services/apartment-renovation'
            | '/services/commercial-fit-out'
            | '/services/bespoke-joinery'
            | '/services/custom-kitchens'
            | '/services/wardrobes'
            | '/services/approvals'
            | '/services/mep-hvac'
            | '/services/materials-procurement'
            | '/projects/coastal-villa-concept'
            | '/projects/garden-villa-concept'
            | '/projects/tower-residence-concept'
            | '/projects/business-district-office-concept';
          id?: string | null;
        }[]
      | null;
    /**
     * Opens the enquiry form (on the current page if it has one, otherwise on /contact).
     */
    ctaLabel: string;
  };
  footer: {
    exploreHeading: string;
    exploreLinks?:
      | {
          label: string;
          route:
            | '/'
            | '/services'
            | '/projects'
            | '/process'
            | '/about'
            | '/insights'
            | '/contact'
            | '/warranty'
            | '/privacy'
            | '/cookies'
            | '/services/interior-design'
            | '/services/landscape-design'
            | '/services/villa-renovation'
            | '/services/apartment-renovation'
            | '/services/commercial-fit-out'
            | '/services/bespoke-joinery'
            | '/services/custom-kitchens'
            | '/services/wardrobes'
            | '/services/approvals'
            | '/services/mep-hvac'
            | '/services/materials-procurement'
            | '/projects/coastal-villa-concept'
            | '/projects/garden-villa-concept'
            | '/projects/tower-residence-concept'
            | '/projects/business-district-office-concept';
          id?: string | null;
        }[]
      | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contact?:
    | T
    | {
        phoneDisplay?: T;
        phoneE164?: T;
        whatsappNumber?: T;
        email?: T;
        workingHours?: T;
        visitsLine?: T;
      };
  legal?:
    | T
    | {
        entityName?: T;
        licenceNumber?: T;
        issuingAuthority?: T;
        activities?: T;
        registeredAddress?: T;
      };
  privacy?:
    | T
    | {
        contactEmail?: T;
        providers?: T;
        retention?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  header?:
    | T
    | {
        servicesLabel?: T;
        serviceGroups?:
          | T
          | {
              label?: T;
              services?: T;
              id?: T;
            };
        specialistLabel?: T;
        specialistServices?: T;
        allServicesLabel?: T;
        links?:
          | T
          | {
              label?: T;
              route?: T;
              id?: T;
            };
        ctaLabel?: T;
      };
  footer?:
    | T
    | {
        exploreHeading?: T;
        exploreLinks?:
          | T
          | {
              label?: T;
              route?: T;
              id?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}